txt = str(input("Digite algo: "))
print("O tipo primitivo desse valor é {}".format(type(txt)))
print("Só tem espaços? {}".format(txt.isspace()))
print("É um numero? {}".format(txt.isnumeric()))
print("É alfabético? {}".format(txt.isalpha()))
print("É alfanumérico? {}".format(txt.isialnum()))
print("Esta em maisuculas? {}".format(txt.isupper()))
print("Esta em minusculas? {}".format(txt.islower()))
print("Esta capitalizada? {}".format(txt.istitle()))
